export const ALL_ASSET_PATHS = [
    "/assets/Akrilik Bulat Baby Blue - Rp 65.000 2.png",
    "/assets/Akrilik Bulat Baby Blue - Rp 65.000.png",
    "/assets/Akrilik Bulat Blue Gold - Rp 65.000 .png",
    "/assets/Akrilik Bulat Blue Gold - Rp 65.000 2.png",
    "/assets/Akrilik Bulat Dusty Blue - Rp 65.000 .png",
    "/assets/Akrilik Bulat Dusty Blue - Rp 65.000 2.png",
    "/assets/Akrilik Marble Pink - Rp 65.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek.png",
    "/assets/Akrilik Persegi Orange -Rp 65.000 - harga sewa per 24jam.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 10.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 2.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 3.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 4.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 5.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 6.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 7.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 8.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan 9.png",
    "/assets/Akrilik frame mini - Rp 95.000 - akrilik dome ukuran A5 standing lampu warna putih bisa request warna foto and tulisan.png",
    "/assets/Bloom Box Bule Gold - 200k .png",
    "/assets/Bloom Box Disgompie - 190k .png",
    "/assets/Bloom Box Disianthus - 200k .png",
    "/assets/Bloom Box Gompie - 250k.png",
    "/assets/Bloom Box Lili Rose - 170k .png",
    "/assets/Bloom Box Lily Kris - 180k .png",
    "/assets/Bloom Box MarieGold - 200k .png",
    "/assets/Bloom Box Medium plus Akrilik - 200k .png",
    "/assets/Bucket Rokok 5 Pcs.png",
    "/assets/Bucket Rokok 6 Pcs.png",
    "/assets/Bucket Rokok Love Pre Order.png",
    "/assets/Bucket Rokok plus Kopi.png",
    "/assets/Bucket Shine Muscat - 150k .png",
    "/assets/Bucket Uang Berdiri 30 Lembar.png",
    "/assets/Bucket Uang Berdiri plus Fresh Flowers .png",
    "/assets/Bucket Uang Kipas plus Fresh Flowers .png",
    "/assets/Buket Bunga Asli Premium - Rp 350.000 2.png",
    "/assets/Buket Bunga Asli Premium - Rp 350.000 3.png",
    "/assets/Buket Bunga Asli Premium - Rp 350.000 4.png",
    "/assets/Buket Bunga Asli Premium - Rp 350.000 5.png",
    "/assets/Buket Bunga Asli Premium - Rp 350.000.png",
    "/assets/Buket Bunga Gradoll Graduation Doll Big Mesh - Rp 170.000 - bunga palsu mix isian tidak bisa sama persis ukuran and jumlah bu 2.png",
    "/assets/Buket Bunga Gradoll Graduation Doll Big Mesh - Rp 170.000 - bunga palsu mix isian tidak bisa sama persis ukuran and jumlah bu.png",
    "/assets/Buket Bunga Gradoll Graduation Doll Big Mesh - Rp 170.000 - bunga palsu mix isian tidak bisa sama persis ukuran and jumlah bunga kurle3.png",
    "/assets/Buket Cilla Estetik Mesh - Rp 150.000 - Isian bunga tidak bisa sama persis untuk jumlah bunga and ukuran buket kurleb sama - bunga palsu premium plus est 2.png",
    "/assets/Buket Cilla Estetik Mesh - Rp 150.000 - Isian bunga tidak bisa sama persis untuk jumlah bunga and ukuran buket kurleb sama - bunga palsu premium plus est 3.png",
    "/assets/Buket Cilla Estetik Mesh - Rp 150.000 - Isian bunga tidak bisa sama persis untuk jumlah bunga and ukuran buket kurleb sama - bunga palsu premium plus est 4.png",
    "/assets/Buket Cilla Estetik Mesh - Rp 150.000 - Isian bunga tidak bisa sama persis untuk jumlah bunga and ukuran buket kurleb sama - bunga palsu premium plus est.png",
    "/assets/Buket Kawat PO H-7.png",
    "/assets/Buket Skripsi PO H-7.png",
    "/assets/Buket skripsi glitter 20 tangkai - Rp 170.000 - bisa bawa kertas skripsi sendiri bisa request warna and tulisan di pita 2.png",
    "/assets/Buket skripsi glitter 20 tangkai - Rp 170.000 - bisa bawa kertas skripsi sendiri bisa request warna and tulisan di pita 3.png",
    "/assets/Buket skripsi glitter 20 tangkai - Rp 170.000 - bisa bawa kertas skripsi sendiri bisa request warna and tulisan di pita 4.png",
    "/assets/Buket skripsi glitter 20 tangkai - Rp 170.000 - bisa bawa kertas skripsi sendiri bisa request warna and tulisan di pita 5.png",
    "/assets/Buket skripsi glitter 20 tangkai - Rp 170.000 - bisa bawa kertas skripsi sendiri bisa request warna and tulisan di pita.png",
    "/assets/Bunga Artificial MIX - 50K .png",
    "/assets/Bunga Mawar Medium - Rp 100.000 - Bunga mawar asli isi 7tangkai mekar plus tambahan kain salju 20.000 120.000 2.png",
    "/assets/Bunga Mawar Medium - Rp 100.000 - Bunga mawar asli isi 7tangkai mekar plus tambahan kain salju 20.000 120.000 3.png",
    "/assets/Bunga Mawar Medium - Rp 100.000 - Bunga mawar asli isi 7tangkai mekar plus tambahan kain salju 20.000 120.000 4.png",
    "/assets/Bunga Mawar Medium - Rp 100.000 - Bunga mawar asli isi 7tangkai mekar plus tambahan kain salju 20.000 120.000 5.png",
    "/assets/Bunga Mawar Medium - Rp 100.000 - Bunga mawar asli isi 7tangkai mekar plus tambahan kain salju 20.000 120.000.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 2.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 3.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 4.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 5.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 6.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000 7.png",
    "/assets/Bunga Mawar Palsu Premium ukuran Big - Rp 250.000.png",
    "/assets/Bunga mawar palsu small - Rp 50.000 .png",
    "/assets/Bunga mawar palsu small - Rp 50.000 2.png",
    "/assets/Bunga mawar palsu small - Rp 50.000 3.png",
    "/assets/Bunga mawar palsu small - Rp 50.000 4.png",
    "/assets/Bunga mawar palsu small - Rp 50.000 5.png",
    "/assets/Donat buket tart - Rp 100.000 - isi 7 donat bomboloni isi coklat topping glaze bisa request warna. silahkan chat admin 2.png",
    "/assets/Donat buket tart - Rp 100.000 - isi 7 donat bomboloni isi coklat topping glaze bisa request warna. silahkan chat admin 3.png",
    "/assets/Donat buket tart - Rp 100.000 - isi 7 donat bomboloni isi coklat topping glaze bisa request warna. silahkan chat admin.png",
    "/assets/Flowers Sash Ayca - 150K.png",
    "/assets/Frame Birthday Edelweis - Rp 150.000 - frame ukuran 25cm x 35cm - bisa request tulisan plus 2 foto - bunga edelweis mini 2.png",
    "/assets/Frame Birthday Edelweis - Rp 150.000 - frame ukuran 25cm x 35cm - bisa request tulisan plus 2 foto - bunga edelweis mini 3.png",
    "/assets/Frame Birthday Edelweis - Rp 150.000 - frame ukuran 25cm x 35cm - bisa request tulisan plus 2 foto - bunga edelweis mini 4.png",
    "/assets/Frame Birthday Edelweis - Rp 150.000 - frame ukuran 25cm x 35cm - bisa request tulisan plus 2 foto - bunga edelweis mini.png",
    "/assets/Hand-Bucket Anggrek Lily - 450K.png",
    "/assets/Hand-Bucket Anthurium - 425K.png",
    "/assets/Hand-Bucket Artificial - 150K.png",
    "/assets/Hand-Bucket Pearl White - 120k.png",
    "/assets/Hand-Bucket Rose - 300k .png",
    "/assets/Hand-Bucket Sofy - 280K.png",
    "/assets/Karangan Bunga Bunga Papan 1 Titik - Rp 500.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 2.png",
    "/assets/Karangan Bunga Bunga Papan 1 Titik - Rp 500.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 2.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 3.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 4.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 5.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 6.png",
    "/assets/Karangan Bunga Bunga Papan 2 Titik - Rp 600.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala.png",
    "/assets/Karangan Bunga Bunga Papan 3 Titik - Rp 750.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala.png",
    "/assets/Karangan Bunga Bunga Papan 4 titik - Rp 1.000.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangka.png",
    "/assets/Karangan Bunga Full Mega Bintang - Rp 2.000.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala 2.png",
    "/assets/Karangan Bunga Full Mega Bintang - Rp 2.000.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala.png",
    "/assets/Kawat Bulu Lily - 130K.png",
    "/assets/Mawar Candy Big Bunga Asli - Rp 200.000.png",
    "/assets/Mawar Candy Bunga Asli - Rp 170.000 2.png",
    "/assets/Mawar Candy Bunga Asli - Rp 170.000.png",
    "/assets/Peony rose medium - Rp 80.000 - bunga palsu premium peony hologram 2.png",
    "/assets/Peony rose medium - Rp 80.000 - bunga palsu premium peony hologram 3.png",
    "/assets/Peony rose medium - Rp 80.000 - bunga palsu premium peony hologram 4.png",
    "/assets/Peony rose medium - Rp 80.000 - bunga palsu premium peony hologram.png",
    "/assets/Pinky Pearl Fresh Flowers - 500K.png",
    "/assets/Rose gonie pink - Rp 120.000 - Bunga mawar palsu mekar 7 tangkai - bisa request warna chat admin 2.png",
    "/assets/Rose gonie pink - Rp 120.000 - Bunga mawar palsu mekar 7 tangkai - bisa request warna chat admin.png",
    "/assets/Round Bucket Aisyah - 200k.png",
    "/assets/Round Bucket Rose - 150K.png",
    "/assets/Round Bucket Viphone - 250K Iphone dari Customer .png",
    "/assets/Round Elegant Dior Mahkota - Rp 350.000.png",
    "/assets/Round Elegant Dior non Mahkota - Rp 320.000.png",
    "/assets/Round Pita Satin - Rp 100.000 2.png",
    "/assets/Round Pita Satin - Rp 100.000 3.png",
    "/assets/Round Pita Satin - Rp 100.000.png",
    "/assets/Round Pita Satin 8 Tangkai - 150k.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 2.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 3.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 4.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 5.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 6.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 7.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000 8.png",
    "/assets/Selempang Wisuda 3 Titik - Rp 95.000.png",
    "/assets/Selempang Wisuda 3Titik Garis - Rp 105.000 .png",
    "/assets/Selempang Wisuda 3Titik Garis - Rp 105.000 2.png",
    "/assets/Selempang list pita - Rp 75.000.png",
    "/assets/Sewa Kostum Kayla - Start 300k .png",
    "/assets/Sewa Kostum Kayla - Start 350k .png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 10.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 2.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 3.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 4.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 5.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 6.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 7.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 8.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah 9.png",
    "/assets/Sewa Standing Akrilik PROMO - Rp 40.000 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready set 2.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready set.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready setiap hari 2.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready setiap hari 3.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready setiap hari 4.png",
    "/assets/Sewa Standing Akrilik bulat PROMO - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 -bisa untuk segala acara Ready setiap hari 3.png",
    "/assets/Standing Akrilik Bulat 2.png",
    "/assets/Standing Akrilik Bulat.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 2.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 3.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 4.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 5.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 6.png",
    "/assets/Standing akrilik Dome - Rp 70.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 7.png",
    "/assets/Tabung Boneka isi Perhiasan Pre Order .png",
    "/assets/Thmbelina Miuw - 350k .png",
    "/assets/Thumbelina Aycaa - 350K.png",
    "/assets/Thumbelina Ayu - 150k .png",
    "/assets/Thumbelina Bebebb - 400k .png",
    "/assets/Thumbelina BlueBaby - 180k .png",
    "/assets/Thumbelina Butterfly Holo - 400k .png",
    "/assets/Thumbelina Duolily - 300k .png",
    "/assets/Thumbelina Faza - 135k .png",
    "/assets/Thumbelina Kriwil - 200K.png",
    "/assets/Thumbelina Lily Love - 180k .png",
    "/assets/Thumbelina Mini Rose - 100k .png",
    "/assets/Thumbelina Miuw - 300k.png",
    "/assets/Thumbelina Nanat.png",
    "/assets/Thumbelina Ntan Fresh Flowers - 500k .png",
    "/assets/Thumbelina Round - 250K.png",
    "/assets/Thumbelina Round Lily - 250k .png",
    "/assets/Thumbelina Sassy - 100k.png",
    "/assets/Thumbelina Small - 100K .png",
    "/assets/Thumbelina Sofi - 220k .png",
    "/assets/Vas Keranjang Loveely Bunga Import - 500k .png",
    "/assets/Vas Lily Premium - 400k .png",
    "/assets/bunga white sedap - Rp 125.000 - 125ribu hanya bunga asli saja 10tangkai sedap malam and 10tangkai asteria 2.png",
    "/assets/bunga white sedap - Rp 125.000 - 125ribu hanya bunga asli saja 10tangkai sedap malam and 10tangkai asteria 3.png",
    "/assets/bunga white sedap - Rp 125.000 - 125ribu hanya bunga asli saja 10tangkai sedap malam and 10tangkai asteria.png",
    "/assets/packing luxury elegant - Rp 25.000 - packing box plus kertas plus pita organza 2.png",
    "/assets/packing luxury elegant - Rp 25.000 - packing box plus kertas plus pita organza 3.png",
    "/assets/packing luxury elegant - Rp 25.000 - packing box plus kertas plus pita organza.png",
    "/assets/standing akrilik bulat - Rp 65.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 2.png",
    "/assets/standing akrilik bulat - Rp 65.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek 3.png",
    "/assets/standing akrilik bulat - Rp 65.000 - harga sewa per 24jam bisa request tulisan and warna bunga bisa diambil dikirim kurir ay jek.png"
] as const;
