
  // ======= AY BUKET — CURATED PREMIUM COLLECTION (11 items) =======
  { id: "ay-accessories-1", name: "Akrilik Frame Mini", category: "accessories", price: 95000, priceLabel: "Rp 95.000", image: "/assets/Akrilik frame mini - Rp 95.000,00 - akrilik dome ukuran A5 standing lampu warna putih, bisa request warna, foto & tulisan (10).png", tag: "Favorit Kami" },
  { id: "ay-accessories-2", name: "Sewa Per Jam Standing Akrilik Bulat", category: "accessories", price: 40000, priceLabel: "Rp 40.000", image: "/assets/Sewa Standing Akrilik bulat (PROMO) - sewa 3 jam Rp 40.000 - sewa 12 jam Rp 50.000 - sewa 24jam Rp 75.000 - bisa untuk segala acara Ready set (2).png", tag: "Favorit Kami" },
  { id: "ay-buckets-3", name: "Bucket Aesthetic", category: "buckets", price: 100000, priceLabel: "Rp 100.000", image: "/assets/Round Pita Satin - Rp 100.000,00 (2).png", tag: "Favorit Kami" },
  { id: "ay-buckets-4", name: "Bucket Bunga Gradoll (graduation Doll) Big Mesh", category: "buckets", price: 170000, priceLabel: "Rp 170.000", image: "/assets/Buket Bunga Gradoll (Graduation Doll) Big Mesh - Rp 170.000,00 - bunga palsu mix isian tidak bisa sama persis, ukuran & jumlah bu (2).png" },
  { id: "ay-fresh-flower-5", name: "Bunga Mawar Palsu", category: "fresh-flower", price: 250000, priceLabel: "Rp 250.000", image: "/assets/Bunga Mawar Palsu Premium (ukuran Big) - Rp 250.000,00 (2).png" },
  { id: "ay-fresh-flower-6", name: "Bunga White Sedap", category: "fresh-flower", price: 125000, priceLabel: "Rp 125.000", image: "/assets/bunga white sedap - Rp 125.000,00 - 125ribu hanya bunga asli saja (10tangkai sedap malam & 10tangkai asteria) (2).png" },
  { id: "ay-catalog-home-7", name: "Frmae Birthday Edelweis", category: "catalog-home", price: 150000, priceLabel: "Rp 150.000", image: "/assets/Frame Birthday Edelweis - Rp 150.000,00 - frame ukuran 25cm x 35cm - bisa request tulisan + 2 foto - bunga edelweis mini (2).png" },
  { id: "ay-catalog-home-8", name: "Mawar Candy (bunga Asli)", category: "catalog-home", price: 170000, priceLabel: "Rp 170.000", image: "/assets/Mawar Candy (Bunga Asli) - Rp 170.000,00 (2).png" },
  { id: "ay-wreaths-9", name: "Karangan Bunga", category: "wreaths", price: 500000, priceLabel: "Rp 500.000", image: "/assets/Karangan Bunga Bunga Papan 1 Titik - Rp 500.000,00 - Karangan Bunga Bunga Papan bisa untuk segala acara Ready setiap hari bisa dikirim Kamal Telang Socah Bangkala (2).png" },
  { id: "ay-packaging-10", name: "Packing Luxury Elegant", category: "packaging", price: 25000, priceLabel: "Rp 25.000", image: "/assets/packing luxury elegant - Rp 25.000,00 - packing box + kertas + pita organza (2).png" },
  { id: "ay-ribbons-11", name: "Selempang Wisuda 3 Titik", category: "ribbons", price: 95000, priceLabel: "Rp 95.000", image: "/assets/Selempang Wisuda 3 Titik - Rp 95.000,00 (2).png" },
